### ISSUE TITLE
APIConnectionError: Connection error

### ISSUE THREAD

**Issue by ydyleo** [chanpreet3000/amazon-hackon#1]
![1701621416050](https://github.com/chanpreet3000/amazon-hackon/assets/63301398/a1554263-6825-469a-a307-81905d274540)

**Comment by chanpreet3000** [comment]
hi @ydyleo, please provide the full error message?

**Comment by ydyleo** [comment]
> hi @ydyleo, please provide the full error message?

when creating embeddings here, meet the error:
![image](https://github.com/chanpreet3000/amazon-hackon/assets/63301398/6780bb38-57f2-463f-bbe4-2ca53652f6f0)
I dont know whether it is a connect error when connecting to langchain, how can I fix this

**Comment by chanpreet3000** [comment]
Still  you have not provided the full error message. Just copy paste the whole text. Btw have you configured the backend’s .env file it should have the openai api key.

**Comment by ydyleo** [comment]
> Still you have not provided the full error message. Just copy paste the whole text. Btw have you configured the backend’s .env file it should have the openai api key.

Yeah I have set the openai key. I found it was a connection error and check the proxy, because I just went back to China.
